'''
Author: shaoting0730 510738319@qq.com
Date: 2026-09-19 15:57:56
LastEditors: shaoting0730 510738319@qq.com
LastEditTime: 2026-09-19 16:25:21
FilePath: /学习代码/09-agent-basic-stream.py
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
'''

from langchain.agents import create_agent


from dotenv import load_dotenv
load_dotenv()

def get_weather(city:str) -> str:
    """查询天气如何"""
    return f"今天{city}天气是多云转晴"

agent = create_agent(
    model="deepseek:deepseek-chat",
    tools=[get_weather]
)


# for event in agent.stream(
#     {"messages":[{"role":"user","content":"杭州天气如何？"}]},
#     stream_mode="values",
# ):
#     messages = event["messages"]
#     # for message in messages:
#     #    print(f"~~~~~~~~~~~~~~~~历史消息：{len(messages)} 条")
#     #    message.pretty_print()
#     messages[-1].pretty_print()

for chunk in agent.stream(
    {"messages":[{"role":"user","content":"杭州天气如何？"}]},
    stream_mode="messages",
):
#    print(chunk);    
   print(chunk[0].content,end='')
#    (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='I', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content="'ll", additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' check', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' the', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' weather', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' in', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' Hang', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='zhou', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' for', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content=' you', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='.', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[{'name': 'get_weather', 'args': {}, 'id': 'call_00_Ljjxrbd5HLPqG5bolzJV9993', 'type': 'tool_call'}], invalid_tool_calls=[], tool_call_chunks=[{'name': 'get_weather', 'args': '', 'id': 'call_00_Ljjxrbd5HLPqG5bolzJV9993', 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[{'name': '', 'args': {}, 'id': None, 'type': 'tool_call'}], invalid_tool_calls=[], tool_call_chunks=[{'name': None, 'args': '{', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': '"', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': '"', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': 'city', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': 'city', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': '"', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': '"', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': ': ', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': ': ', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': '"', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': '"', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': '杭州', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': '杭州', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': '"', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': '"', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[{'name': None, 'args': '}', 'id': None, 'error': None, 'type': 'invalid_tool_call'}], tool_call_chunks=[{'name': None, 'args': '}', 'id': None, 'index': 0, 'type': 'tool_call_chunk'}]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'finish_reason': 'tool_calls', 'model_name': 'deepseek-flash', 'system_fingerprint': 'aeb56401ca74e127821c4f9126dcb669', 'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 266, 'output_tokens': 48, 'total_tokens': 314, 'input_token_details': {'cache_read': 128}, 'output_token_details': {}}, tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={}, id='lc_run--01a0b8c3-5312-7111-90c2-ea06096d9448', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[], chunk_position='last'), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 1, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'checkpoint_ns': 'model:7a6b2334-5418-3aa0-ba2b-af55c21b26cd', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (ToolMessage(content='今天杭州天气是多云转晴', name='get_weather', id='63ea7a33-541e-4583-a940-ce823ea11ac4', tool_call_id='call_00_Ljjxrbd5HLPqG5bolzJV9993'), {'ls_integration': 'langchain_create_agent', 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('__pregel_push',), 'langgraph_path': ('__pregel_push', 0, False), 'langgraph_checkpoint_ns': 'tools:d6026693-1946-0367-b919-d4fd6debe8cd'})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='杭州', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='今天', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='天气', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='是', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='**', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='多云', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='转', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='晴', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='**', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='，', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='总体', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='还不错', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='，', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='适合', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='外出', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='活动', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='。', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='建议', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='出门', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='时', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='还是', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='带', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='件', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='薄', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='外套', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='，', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='早晚', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='温差', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='可能', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='稍', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='大', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='。\n\n', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='需要', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='我', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='帮你', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='查', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='其他', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='城市的', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='天气', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'),'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='吗', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='？', additional_kwargs={}, response_metadata={'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={'finish_reason': 'stop', 'model_name': 'deepseek-flash', 'system_fingerprint': 'aeb56401ca74e127821c4f9126dcb669', 'model_provider': 'deepseek'}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 333, 'output_tokens': 41, 'total_tokens': 374, 'input_token_details': {'cache_read': 128}, 'output_token_details': {}}, tool_call_chunks=[]), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_type': 'chat', 'ls_temperature': None, 'lc_versions': {'langchain-core': '1.6.2', 'langchain': '1.4.0', 'langchain-openai': '1.6.2'}})
# (AIMessageChunk(content='', additional_kwargs={}, response_metadata={}, id='lc_run--01a0b8c3-56b8-7ed2-9607-a7ab093326ac', tool_calls=[], invalid_tool_calls=[], tool_call_chunks=[], chunk_position='last'), {'ls_integration': 'langchain_chat_model', 'langgraph_step': 3, 'langgraph_node': 'model', 'langgraph_triggers': ('branch:to:model',), 'langgraph_path': ('__pregel_pull', 'model'), 'langgraph_checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'checkpoint_ns': 'model:b74a6668-65ec-60b4-f0a3-410a4a4a20aa', 'ls_provider': 'deepseek', 'ls_model_name': 'deepseek-chat', 'ls_model_typ